import { generateRepoName, makeFakeRepo } from '@/lib/gh/fake';

describe('fake', () => {
    describe('generateRepoName', () => {
        it('should generate a repo name with prefix, object and quality', () => {
            const name = generateRepoName();

            expect(name).toBeTruthy();
            expect(typeof name).toBe('string');
            expect(name.length).toBeGreaterThan(0);
            expect(name).toMatch(/de/);
        });

        it('should generate different names on multiple calls', () => {
            const names = Array.from({ length: 10 }, () => generateRepoName());
            const uniqueNames = new Set(names);

            expect(uniqueNames.size).toBeGreaterThan(1);
        });
    });

    describe('makeFakeRepo', () => {
        it('should generate a valid GHRepo object', () => {
            const repo = makeFakeRepo();

            expect(repo).toHaveProperty('id');
            expect(repo).toHaveProperty('name');
            expect(repo).toHaveProperty('description');
            expect(repo).toHaveProperty('stargazers_count');
            expect(repo).toHaveProperty('language');
            expect(repo).toHaveProperty('html_url');
            expect(repo).toHaveProperty('updated_at');
        });

        it('should generate repo with valid id range', () => {
            const repo = makeFakeRepo();

            expect(repo.id).toBeGreaterThanOrEqual(1000000);
            expect(repo.id).toBeLessThanOrEqual(9999999);
        });

        it('should generate repo with valid name', () => {
            const repo = makeFakeRepo();

            expect(repo.name).toBeTruthy();
            expect(typeof repo.name).toBe('string');
            expect(repo.name.length).toBeGreaterThan(0);
        });

        it('should generate repo with valid description', () => {
            const repo = makeFakeRepo();

            expect(repo.description).toBeTruthy();
            expect(typeof repo.description).toBe('string');
        });

        it('should generate repo with valid stargazers_count', () => {
            const repo = makeFakeRepo();

            expect(repo.stargazers_count).toBeGreaterThanOrEqual(0);
            expect(repo.stargazers_count).toBeLessThanOrEqual(5000);
        });

        it('should generate repo with valid language', () => {
            const repo = makeFakeRepo();

            if (repo.language !== null) {
                expect(typeof repo.language).toBe('string');
                expect(repo.language.length).toBeGreaterThan(0);
            } else {
                expect(repo.language).toBeNull();
            }
        });

        it('should generate repo with valid html_url', () => {
            const repo = makeFakeRepo();

            expect(repo.html_url).toMatch(/^https:\/\/github\.com\/example\//);
            expect(repo.html_url).toContain(repo.name);
        });

        it('should generate repo with valid updated_at ISO date', () => {
            const repo = makeFakeRepo();

            expect(repo.updated_at).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
            const date = new Date(repo.updated_at);
            expect(date.getTime()).not.toBeNaN();
        });

        it('should generate different repos on multiple calls', () => {
            const repos = Array.from({ length: 10 }, () => makeFakeRepo());
            const uniqueIds = new Set(repos.map(r => r.id));

            expect(uniqueIds.size).toBeGreaterThan(5);
        });

        it('should generate repo with description or fallback text', () => {
            const repos = Array.from({ length: 20 }, () => makeFakeRepo());

            const hasDescription = repos.some(r => r.description && r.description !== 'Repo generated by fake data');
            const hasFallback = repos.some(r => r.description === 'Repo generated by fake data');

            expect(hasDescription || hasFallback).toBe(true);
        });
    });
});

