export const PREFIXES = [
    "gerador",
    "criador",
    "executador",
    "processador",
    "indexador",
    "agregador",
    "normalizador",
    "localizador",
    "catalogador",
    "orquestrador",
    "controlador",
    "aplicador",
    "transformador",
    "integrador",
    "validador",
    "abstração",
    "engine",
    "parser",
    "resolver",
    "modulador",
] as const;

export const OBJECTS = [
    "lojas",
    "websites",
    "aplicações",
    "landing pages",
    "sistemas",
    "dashboards",
    "pipelines",
    "APIs",
    "conteúdos",
    "documentos",
    "componentes",
    "assets",
    "projetos",
    "imagens",
    "arquivos",
    "relatórios",
    "processos",
    "microserviços",
    "interfaces",
] as const;

export const QUALITIES = [
    "rápido",
    "eficiente",
    "inteligente",
    "automático",
    "simples",
    "robusto",
    "incrível",
    "moderno",
    "experimental",
    "decente",
    "bem feito",
    "sem complicação",
    "minimalista",
    "acelerado",
    "otimizado",
    "avançado",
] as const;

export const LANGUAGES = [
    "TypeScript",
    "JavaScript",
    "Go",
    "Python",
    "Rust",
    "PHP",
    "C#",
    "C++",
    "Java",
    null,
] as const;