import { LANGUAGES, OBJECTS, PREFIXES, QUALITIES } from "./consts";
import { GHRepo } from "./types";

const randomInt = (min: number, max: number): number =>
    Math.floor(Math.random() * (max - min + 1)) + min;

const randomChoice = <T>(arr: readonly T[]): T =>
    arr[randomInt(0, arr.length - 1)];

const randomWord = () =>
    Math.random().toString(36).substring(2, 8);

const randomSentence = (words = 6) =>
    Array.from({ length: words }, randomWord).join(" ");

const randomDateISO = () =>
    new Date(Date.now() - randomInt(0, 1000 * 60 * 60 * 24 * 365)).toISOString();

export function generateRepoName(): string {
    const prefix = randomChoice(PREFIXES);
    const object = randomChoice(OBJECTS);
    const quality = randomChoice(QUALITIES);

    return `${prefix} de ${object} ${quality}`;
}

export function makeFakeRepo(): GHRepo {
    const name = generateRepoName();

    return {
        id: randomInt(1000000, 9999999),
        name,
        description: Math.random() > 0.3 ? randomSentence(8) : "Repo generated by fake data",
        stargazers_count: randomInt(0, 5000),
        language: randomChoice(LANGUAGES),
        html_url: `https://github.com/example/${name}`,
        updated_at: randomDateISO(),
    } as const;
}